# Generated by Django 3.0.8 on 2020-07-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0002_fornecedor_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cor.Pessoa')),
                ('cnpj', models.CharField(max_length=20)),
            ],
            bases=('cor.pessoa',),
        ),
        migrations.CreateModel(
            name='pessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cor.Pessoa')),
                ('data_de_Nacimento', models.CharField(blank=True, max_length=10)),
                ('CPF', models.CharField(max_length=20)),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Sexo', verbose_name='Sexo')),
            ],
            bases=('cor.pessoa',),
        ),
    ]
