# Generated by Django 3.0.8 on 2020-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0003_pesoajuridica_pessoafisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=11)),
            ],
        ),
    ]
