# Generated by Django 3.0.8 on 2020-07-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=70)),
                ('codigo', models.CharField(blank=True, max_length=13)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estoque', models.CharField(blank=True, max_length=12)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Categoria', verbose_name='Categoria')),
            ],
        ),
    ]
