# Generated by Django 3.0.8 on 2020-07-08 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0005_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(blank=True, max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Produto', verbose_name='Produto')),
            ],
        ),
    ]
