# Generated by Django 3.0.8 on 2020-07-08 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0006_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.fornecedor', verbose_name='fornecedor')),
                ('produto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Produto', verbose_name='Produto')),
            ],
        ),
    ]
