# Generated by Django 3.0.8 on 2020-07-08 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0007_entradamercadoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosExrtas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
