# Generated by Django 3.0.8 on 2020-07-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0008_gastosexrtas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamercadoria',
            name='quantidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
