# Generated by Django 3.0.8 on 2020-07-12 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cor', '0009_auto_20200708_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(blank=True, max_length=12, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataHora', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caixa',
            },
        ),
    ]
