# Generated by Django 3.0.8 on 2020-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0010_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
