# Generated by Django 3.0.8 on 2020-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0011_auto_20200717_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='quantidade',
            field=models.IntegerField(default=0, max_length=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
