# Generated by Django 3.0.8 on 2020-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0012_auto_20200720_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercadoria',
            name='quantidade',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='quantidade',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
